# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  deploy-to-coopernetes:
    docker:
      - image: colabcoop/coopernetes-deploy:0.3.3
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - setup_remote_docker
      - run: /deploy.sh
  staging_ui:
    docker:
      - image: circleci/python:3.6
    steps:
      - add_ssh_keys:
          fingerprints:
            - "94:a6:df:e0:d7:c5:92:55:dc:80:73:c2:29:67:18:7d"
            - "1a:51:45:73:23:c6:45:e5:98:9f:70:21:78:71:81:a1"
      - checkout
      - run:
          name: Clone Operations Repository
          command: |
            git clone git@bitbucket.org:colabcoop-ondemand/hvbp-operations.git ~/operations
      - restore_cache:
          keys:
          - deps-{{ checksum "~/operations/ansible/ui/requirements.txt" }}
      - run:
          name: Install PIP Dependencies
          command: |
            python3 -m venv env
            . env/bin/activate
            pip install -r ~/operations/ansible/ui/requirements.txt
      - save_cache:
          key: deps-{{ checksum "~/operations/ansible/ui/requirements.txt" }}
          paths:
            - "env"
      - run:
          name: Setup Ansible Vault pass
          command: |
            echo $VAULT_PASS | tee ~/operations/ansible/ui/.vault-pass
      - run:
          name: Deploy with Ansible
          command: |
            . env/bin/activate
            cd ~/operations/ansible/ui
            ansible-playbook -i hosts deploy.yml --limit staging_v1 --vault-password-file ~/operations/ansible/ui/.vault-pass
  production_ui:
    docker:
      - image: circleci/python:3.6
    steps:
      - add_ssh_keys:
          fingerprints:
            - "94:a6:df:e0:d7:c5:92:55:dc:80:73:c2:29:67:18:7d"
            - "1a:51:45:73:23:c6:45:e5:98:9f:70:21:78:71:81:a1"
      - checkout
      - run:
          name: Clone Operations Repository
          command: |
            git clone git@bitbucket.org:colabcoop-ondemand/hvbp-operations.git ~/operations
      - restore_cache:
          keys:
          - deps-{{ checksum "~/operations/ansible/ui/requirements.txt" }}
      - run:
          name: Install PIP Dependencies
          command: |
            python3 -m venv env
            . env/bin/activate
            pip install -r ~/operations/ansible/ui/requirements.txt
      - save_cache:
          key: deps-{{ checksum "~/operations/ansible/ui/requirements.txt" }}
          paths:
            - "env"
      - run:
          name: Setup Ansible Vault pass
          command: |
            echo $VAULT_PASS | tee ~/operations/ansible/ui/.vault-pass
      - run:
          name: Deploy with Ansible
          command: |
            . env/bin/activate
            cd ~/operations/ansible/ui
            ansible-playbook -i hosts deploy.yml --limit production_v1 --vault-password-file ~/operations/ansible/ui/.vault-pass
workflows:
  deploy:
    jobs:
      - deploy-to-coopernetes:
          context: coopernetes-staging
          filters:
            branches:
              only: develop
      - staging_ui:
          filters:
            branches:
              only: ambassador-stage
      - production_ui:
          filters:
            branches:
              only: ambassador
